spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/pumpkinMarket?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      # 连接池名
      pool-name: DateHikarCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间(默认600000 10分钟)
      idle-timeout: 1800000
      # 最大连接数(默认10)
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: PT10S
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: PT1S
        max-active: 8
server:
  port: 8081